addSbtPlugin("org.scalameta"   % "sbt-scalafmt"    % "2.5.0")
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "3.1.3")
addSbtPlugin("ch.epfl.scala"   % "sbt-scalafix"    % "0.11.0")
addSbtPlugin("org.typelevel"   % "sbt-tpolecat"    % "0.5.0")
addSbtPlugin("com.github.sbt"  % "sbt-dynver"      % "5.0.1")
