addSbtPlugin("org.scalameta"             % "sbt-scalafmt"    % "2.5.0")
addSbtPlugin("org.wartremover"           % "sbt-wartremover" % "3.1.3")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"    % "0.11.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"    % "0.4.2")
addSbtPlugin("com.dwijnand"              % "sbt-dynver"      % "4.1.1")
